### ISSUE TITLE
can you add these stuff ?

### ISSUE THREAD

**Issue by DaMonkeExe** [Pixelsuft/hl#2]
could you add these stuff to the site ?

Half life deathmatch
Half life blue shift

**Comment by Pixelsuft** [comment]
Half-Life blue shift crashes when I'm using splitted zip file (because of 100MB size of 1 file limit).
About DM, #1

**Comment by DaMonkeExe** [comment]
oh ok thanks for the reply, but is there any kind of way to embed the game to a site ?

**Comment by Pixelsuft** [comment]
i think yes

**Comment by DaMonkeExe** [comment]
ill add you on discord but you seem to not accept friend requests so add me here at Gordon Freeman#3759

**Comment by Pixelsuft** [comment]
sorry, I have no free time

**Comment by DaMonkeExe** [comment]
oh ok
